-- Supabase Migration: Initial Schema
-- Converting the applyai.db SQLite schema to PostgreSQL

-- Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    company_domain TEXT,
    location TEXT,
    remote_type TEXT CHECK(remote_type IN ('remote', 'hybrid', 'onsite', 'unknown')),
    salary_min INTEGER,
    salary_max INTEGER,
    job_url TEXT NOT NULL UNIQUE,
    ats_type TEXT CHECK(ats_type IN ('greenhouse', 'lever', 'workday', 'linkedin', 'generic')),
    jd_raw TEXT,
    jd_summary TEXT,
    posted_at TEXT,
    discovered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    fit_score INTEGER,
    skills_match INTEGER,
    seniority_match TEXT,
    domain_match INTEGER,
    red_flags JSONB,
    green_flags JSONB,
    talking_points JSONB,
    apply_recommendation TEXT,
    scored_at TIMESTAMP WITH TIME ZONE,

    company_summary TEXT,
    company_size TEXT,
    funding_stage TEXT,
    recent_news JSONB,
    glassdoor_rating REAL,
    researched_at TIMESTAMP WITH TIME ZONE,

    status TEXT DEFAULT 'discovered' CHECK(status IN (
        'discovered', 'scored', 'queued', 'cover_letter_ready',
        'applying', 'applied', 'viewed', 'interview', 'rejected', 'offer'
    )),
    cover_letter TEXT,
    tailored_resume_path TEXT,
    applied_at TIMESTAMP WITH TIME ZONE,
    follow_up_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Settings Table (for preferences.json and similar)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL
);

-- Application Log Table
CREATE TABLE IF NOT EXISTS public.application_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT REFERENCES public.jobs(id) ON DELETE CASCADE,
    event TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_url ON public.jobs(job_url);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);
